import { Product, ProductCategory } from "./types";

export const products = [
  {
    id: "ipad-pro",
    name: "iPad Pro",
    description: "Mỏng không tưởng. Mạnh không ngờ.",
    status: "Theo dõi để biết khi có hàng",
    image: "/api/placeholder/1200/600",
    theme: "dark",
  },
  {
    id: "ipad-air",
    name: "iPad Air",
    description: "Hai kích cỡ. Chip nhanh hơn. Đa zi năng.",
    status: "Theo dõi để biết khi có hàng",
    image: "/api/placeholder/1200/600",
    theme: "light",
  },
];
export const images = [
  { src: "/card/1.png", alt: "Image 1" },
  { src: "/card/2.png", alt: "Image 2" },
  { src: "/card/3.png", alt: "Image 3" },
];

export const searchProducts: Product[] = [
  {
    id: "ipad-pro",
    name: "iPad Pro",
    description: "Mỏng không tưởng. Mạnh không ngờ.",
    productImages: ["/api/placeholder/1200/600"],
    basePrice: 999,
    material: ["Aluminum"],
    color: ["Silver", "Space Gray"],
    category: ProductCategory.Ipad,
    createdAt: new Date(),
    stock: 50,
    updatedAt: new Date(),
    productOptions: [
      {
        id: "option1",
        productId: "ipad-pro",
        color: "Silver",
        material: "Aluminum",
        price: 999,
        stock: 25,
      },
      {
        id: "option2",
        productId: "ipad-pro",
        color: "Space Gray",
        material: "Aluminum",
        price: 999,
        stock: 25,
      },
    ],
  },
  {
    id: "ipad-air",
    name: "iPad Air",
    description: "Hai kích cỡ. Chip nhanh hơn. Đa zi năng.",
    productImages: ["/api/placeholder/1200/600"],
    basePrice: 599,
    material: ["Aluminum"],
    color: ["Rose Gold", "Silver", "Space Gray"],
    category: ProductCategory.Ipad,
    createdAt: new Date(),
    stock: 30,
    updatedAt: new Date(),
    productOptions: [
      {
        id: "option1",
        productId: "ipad-air",
        color: "Rose Gold",
        material: "Aluminum",
        price: 599,
        stock: 15,
      },
      {
        id: "option2",
        productId: "ipad-air",
        color: "Silver",
        material: "Aluminum",
        price: 599,
        stock: 15,
      },
      {
        id: "option3",
        productId: "ipad-air",
        color: "Space Gray",
        material: "Aluminum",
        price: 599,
        stock: 15,
      },
    ],
  },
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    description: "Titan. Siêu bền. Siêu nhẹ.",
    productImages: ["/api/placeholder/1200/600"],
    basePrice: 999,
    material: ["Titanium"],
    color: ["Black Titanium", "White Titanium", "Blue Titanium"],
    category: ProductCategory.Iphone,
    createdAt: new Date(),
    stock: 40,
    updatedAt: new Date(),
    productOptions: [
      {
        id: "option1",
        productId: "iphone-15-pro",
        color: "Black Titanium",
        material: "Titanium",
        price: 999,
        stock: 20,
      },
      {
        id: "option2",
        productId: "iphone-15-pro",
        color: "White Titanium",
        material: "Titanium",
        price: 999,
        stock: 20,
      },
    ],
  },
  {
    id: "macbook-pro-m3",
    name: "MacBook Pro M3",
    description: "Sức mạnh đỉnh cao, tốc độ vượt trội.",
    productImages: ["/api/placeholder/1200/600"],
    basePrice: 1999,
    material: ["Aluminum"],
    color: ["Silver", "Space Gray"],
    category: ProductCategory.Macbook,
    createdAt: new Date(),
    stock: 20,
    updatedAt: new Date(),
    productOptions: [
      {
        id: "option1",
        productId: "macbook-pro-m3",
        color: "Silver",
        material: "Aluminum",
        price: 1999,
        stock: 10,
      },
      {
        id: "option2",
        productId: "macbook-pro-m3",
        color: "Space Gray",
        material: "Aluminum",
        price: 1999,
        stock: 10,
      },
    ],
  },
  {
    id: "apple-watch-ultra-2",
    name: "Apple Watch Ultra 2",
    description: "Bền bỉ, mạnh mẽ, sẵn sàng mọi thử thách.",
    productImages: ["/api/placeholder/1200/600"],
    basePrice: 799,
    material: ["Titanium"],
    color: ["Titanium"],
    category: ProductCategory.AppleWatch,
    createdAt: new Date(),
    stock: 25,
    updatedAt: new Date(),
    productOptions: [
      {
        id: "option1",
        productId: "apple-watch-ultra-2",
        color: "Titanium",
        material: "Titanium",
        price: 799,
        stock: 25,
      },
    ],
  },
  {
    id: "airpods-pro-2",
    name: "AirPods Pro (2nd Gen)",
    description: "Chống ồn chủ động, âm thanh tuyệt vời.",
    productImages: ["/api/placeholder/1200/600"],
    basePrice: 249,
    material: ["Plastic"],
    color: ["White"],
    category: ProductCategory.AirPod,
    createdAt: new Date(),
    stock: 60,
    updatedAt: new Date(),
    productOptions: [
      {
        id: "option1",
        productId: "airpods-pro-2",
        color: "White",
        material: "Plastic",
        price: 249,
        stock: 60,
      },
    ],
  },
];
